version: '2'

services:
### Caddy Server Container ##################################

      caddy:
        build: ./caddy
        volumes:
          - ${CADDY_CUSTOM_CADDYFILE}:/etc/Caddyfile
          - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
          - ${DATA_SAVE_PATH}:/root/.caddy
          - ${PUBLIC_HTML}:/var/www/public
        ports:
          - "${CADDY_HOST_HTTP_PORT}:80"
          - "${CADDY_HOST_HTTPS_PORT}:443"
        networks:
          - frontend
          - backend


### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################
volumes:
    caddy:
      driver: "local"